title: Henrique Boldrin
description: My personal portfolio and projects
markdown: kramdown

baseurl: 
url: https://henrique-fb.github.io


reading_time:
  minute_singular: "min"  # default: minute
  minute_plural: "min"    # default: minutes